---
all:
  children:
    ios:
      hosts:
        switch-1:
          ansible_host: 10.0.0.1
          ansible_user: cisco
          ansible_password: cisco

    nxos:
      hosts:
        switch-2:
          ansible_host: 10.0.0.2
          ansible_user: cisco
          ansible_password: cisco
